#include "lex.h"
#include "asm.h"
#include "gram.h"
#include "parse.h"
#include "utils.h"
#include "utstring.h"
#include <assert.h>
#include <ctype.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#ifdef _WIN32
#include <io.h>
#endif

#define YY_NO_UNISTD_H
#define YY_DECL static int yylex_1(void)


#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types.
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t;
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state* YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE* yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

#define YY_LESS_LINENO(n)
#define YY_LINENO_REWIND_TO(ptr)

/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state {
    FILE* yy_input_file;

    char* yy_ch_buf;		/* input buffer */
    char* yy_buf_pos;		/* current position in input buffer */

    /* Size of input buffer in bytes, not including room for EOB
     * characters.
     */
    int yy_buf_size;

    /* Number of characters read into yy_ch_buf, not including EOB
     * characters.
     */
    int yy_n_chars;

    /* Whether we "own" the buffer - i.e., we know we created it,
     * and can realloc() it to grow it, and should free() it to
     * delete it.
     */
    int yy_is_our_buffer;

    /* Whether this is an "interactive" input source; if so, and
     * if we're using stdio for input, then we want to use getc()
     * instead of fread(), to make sure we stop fetching input after
     * each newline.
     */
    int yy_is_interactive;

    /* Whether we're considered to be at the beginning of a line.
     * If so, '^' rules will be active on the next match, otherwise
     * not.
     */
    int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

    /* Whether to try to fill the input buffer when we reach the
     * end of it.
     */
    int yy_fill_buffer;

    int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2

};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE* yy_buffer_stack = NULL;  /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char* yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE* input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE* file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE* file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char* base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char* yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char* bytes, int len  );

void* yyalloc ( yy_size_t  );
void* yyrealloc ( void*, yy_size_t  );
void yyfree ( void*  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE* yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char* yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 80
#define YY_END_OF_BUFFER 81
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info {
    flex_int32_t yy_verify;
    flex_int32_t yy_nxt;
};
static const flex_int16_t yy_accept[191] = {
    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,   81,   79,    2,    1,    1,   38,   50,   38,
    38,   38,   38,   72,   38,   38,   24,   24,   24,   24,
    4,   38,   38,   38,   37,   37,   37,   37,   37,   37,
    37,   37,    3,   38,   38,   25,   25,   25,   25,   25,
    25,   25,   25,    7,    6,    6,    8,   68,   52,   52,
    51,   67,   70,   51,   71,   75,   74,   74,   73,   77,
    73,   78,   38,   38,   38,    2,    1,   39,    0,    0,
    0,   41,   44,    5,    4,   24,   24,   24,    0,   20,

    22,   23,   21,    0,   20,   21,    4,   48,   47,   40,
    45,   46,   49,   26,   37,   37,   27,   37,   28,   29,
    37,   30,   31,   37,   32,   43,   42,   25,   25,   25,
    25,   25,    7,    6,    8,    8,    9,   68,   52,   65,
    64,   53,   66,   55,   56,   57,   58,   59,   60,   61,
    62,    0,   63,   70,   69,   71,   75,   74,   77,   76,
    78,    0,    0,    0,    0,   11,   11,    0,   12,   12,
    17,   18,   19,   33,   34,   35,   36,   53,   54,   14,
    14,    0,   13,   13,   10,   10,   15,   53,   16,    0
} ;

static const YY_CHAR yy_ec[256] = {
    0,
    1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
    2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    2,    5,    6,    7,    8,    9,   10,   11,   12,
    12,   13,   12,   12,   14,   15,   16,   17,   18,   19,
    19,   19,   19,   19,   19,   20,   20,   12,   21,   22,
    23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
    33,   34,   33,   33,   33,   35,   33,   36,   37,   33,
    37,   38,   33,   39,   33,   40,   33,   41,   33,   33,
    12,   42,   12,   43,   33,    1,   44,   45,   46,   47,

    48,   49,   33,   50,   33,   33,   33,   51,   33,   52,
    37,   33,   37,   53,   33,   54,   33,   55,   33,   41,
    33,   33,   12,   56,   12,   12,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1
} ;

static const YY_CHAR yy_meta[57] = {
    0,
    1,    1,    2,    2,    1,    3,    1,    1,    1,    1,
    4,    1,    5,    1,    6,    1,    7,    7,    7,    7,
    1,    1,    1,    1,    1,    1,    8,    8,    8,    8,
    8,    8,    6,    6,    6,    6,    6,    6,    6,    6,
    6,    9,    1,    8,    8,    8,    8,    8,    8,    6,
    6,    6,    6,    6,    6,    1
} ;

static const flex_int16_t yy_base[218] = {
    0,
    0,   30,   83,   85,   87,   91,   96,  100,  104,  108,
    112,  114,  116,  127,  131,  133,  316,  315,  314,  313,
    331,  330,  336,  620,  333,  620,  331,  310,  620,  620,
    0,  122,  313,  620,  309,  108,  140,   64,  133,  128,
    0,  140,  298,   49,  144,  137,  309,  164,  298,  297,
    162,  296,  620,  263,  249,  168,  169,  293,  171,  292,
    291,  181,  259,    0,  620,  259,  136,    0,  620,  250,
    620,  227,    0,  244,    0,    0,  620,  240,  620,    0,
    226,    0,  186,  190,    0,  233,  620,  620,  266,  187,
    192,  620,  620,  620,    0,    0,    0,    0,  204,  208,

    0,  620,  210,    0,    0,  620,    0,  620,  620,  620,
    620,  620,  620,  620,  209,  207,  620,  180,  620,  620,
    142,  620,  620,  132,  620,  620,  620,  130,  121,  115,
    111,  102,    0,  620,  198,  223,  620,    0,  620,  620,
    620,  223,  620,  620,  620,  620,  620,  620,  620,  620,
    620,    0,  620,    0,  620,    0,    0,  620,    0,  620,
    0,  230,  192,  213,  299,  620,  332,  250,  620,  243,
    256,  270,    0,  620,  620,  620,  620,  273,    0,  620,
    282,  318,  620,  260,  620,  365,  620,  620,  620,  620,
    414,  423,  432,  441,  450,  459,  468,  471,  479,  485,

    490,  498,  507,  516,  524,  533,  542,  550,  559,  562,
    570,  579,  582,  584,  592,  601,  610
} ;

static const flex_int16_t yy_def[218] = {
    0,
    190,    1,  191,  191,  192,  192,  193,  193,  194,  194,
    195,  195,  196,  196,  197,  197,    1,    2,    1,    2,
    1,    2,  190,  190,  190,  190,  190,  190,  190,  190,
    198,  190,  190,  190,  190,  190,  190,   37,   38,   39,
    199,  190,  190,  190,  200,  200,  200,  200,  200,  200,
    200,  200,  190,  190,  190,  201,  201,  201,  201,  201,
    201,  201,  201,  202,  190,  190,  203,  204,  190,  190,
    190,  190,  205,  190,  206,  207,  190,  190,  190,  208,
    190,  209,  190,  190,  210,  190,  190,  190,  211,  190,
    212,  190,  190,  190,  199,   38,   39,   40,   40,   99,

    99,  190,  190,  213,   99,  190,  199,  190,  190,  190,
    190,  190,  190,  190,  200,  200,  190,  200,  190,  190,
    200,  190,  190,  200,  190,  190,  190,  201,  201,  201,
    201,  201,  202,  190,  203,  203,  190,  204,  190,  190,
    190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
    190,  214,  190,  205,  190,  206,  207,  190,  208,  190,
    209,  215,  190,  216,  217,  190,  211,  190,  190,  212,
    99,  190,  213,  190,  190,  190,  190,  190,  214,  190,
    215,  190,  190,  216,  190,  217,  190,  190,  190,    0,
    190,  190,  190,  190,  190,  190,  190,  190,  190,  190,

    190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
    190,  190,  190,  190,  190,  190,  190
} ;

static const flex_int16_t yy_nxt[677] = {
    0,
    24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
    34,   30,   35,   30,   30,   36,   37,   38,   39,   40,
    41,   42,   43,   44,   30,   30,   45,   46,   47,   48,
    49,   50,   50,   51,   52,   50,   50,   50,   50,   50,
    50,   53,   54,   45,   46,   47,   48,   49,   50,   51,
    52,   50,   50,   50,   50,   55,   56,   57,   58,   59,
    60,   61,   61,   62,   63,   61,   61,   61,   61,   61,
    61,  112,  113,   56,   57,   58,   59,   60,   61,   62,
    63,   61,   61,   61,   61,   65,   66,   65,   66,   69,
    70,  105,   71,   69,   70,   67,   71,   67,   69,   70,

    106,   74,   69,   70,  190,   74,   69,   70,  105,   71,
    69,   70,  177,   71,   77,   78,   77,   78,   77,   78,
    94,  176,   79,   95,   79,  175,   81,   90,   72,   77,
    78,  174,   72,   77,   78,   77,   78,   81,   91,   91,
    190,   79,  177,   79,   98,   98,   98,  117,  136,   97,
    97,  137,  176,   72,  114,   72,   96,   96,   97,   98,
    99,  108,  109,  110,  190,  118,   99,  100,   99,  101,
    99,   99,  123,  102,  120,  116,  103,   99,  114,  117,
    104,  120,  118,   99,  100,   99,  101,   99,   99,  102,
    175,  123,  116,  168,  121,  163,  124,  130,  182,  129,

    168,  131,  162,  162,  162,  182,  164,  164,  170,  170,
    190,  121,  124,  190,  130,  132,  129,  174,  131,  190,
    99,   99,   99,   99,  171,  171,  172,  172,  172,  184,
    184,  132,  140,   99,   86,  136,  160,  141,  137,  178,
    178,  178,  158,  142,  142,  142,  181,  181,  181,  155,
    99,  143,  139,  144,  145,  187,  168,  146,  147,  170,
    170,  134,  148,  168,  149,  150,  151,  152,  153,  125,
    144,  145,  171,  171,  146,  147,  184,  184,  148,  149,
    150,  151,  167,  167,  167,  167,  172,  172,  172,  188,
    188,  188,   89,   89,   89,   89,   89,   89,  181,  181,

    181,  190,  122,  119,  127,  126,  125,  190,  122,   89,
    89,   89,   89,   89,   89,  186,  186,  186,  186,  119,
    111,   93,   92,  189,  182,  165,  165,  165,  165,  165,
    165,  182,   88,   87,   86,  190,   85,   85,   84,   84,
    83,   83,  165,  165,  165,  165,  165,  165,  167,  167,
    167,  167,  190,  190,  190,  190,  190,  190,   89,   89,
    89,   89,   89,   89,  190,  190,  190,  190,  190,  190,
    190,  190,  190,  190,  190,   89,   89,   89,   89,   89,
    89,  186,  186,  186,  186,  190,  190,  190,  190,  190,
    190,  165,  165,  165,  165,  165,  165,  190,  190,  190,

    190,  190,  190,  190,  190,  190,  190,  190,  165,  165,
    165,  165,  165,  165,   64,   64,   64,   64,   64,   64,
    64,   64,   64,   68,   68,   68,   68,   68,   68,   68,
    68,   68,   73,   73,   73,   73,   73,   73,   73,   73,
    73,   75,   75,   75,   75,   75,   75,   75,   75,   75,
    76,   76,   76,   76,   76,   76,   76,   76,   76,   80,
    80,   80,   80,   80,   80,   80,   80,   80,   82,   82,
    82,   82,   82,   82,   82,   82,   82,   89,   89,  107,
    190,  107,  107,  107,  107,  107,  107,  107,  115,  190,
    115,  115,  115,  128,  190,  128,  128,  128,  133,  190,

    133,  133,  190,  133,  133,  133,  133,  135,  190,  135,
    135,  135,  135,  135,  135,  135,  138,  190,  190,  138,
    138,  138,  138,  138,  154,  190,  190,  154,  154,  154,
    154,  154,  154,  156,  190,  190,  156,  156,  156,  156,
    156,  156,  157,  190,  157,  190,  157,  157,  157,  157,
    159,  190,  159,  190,  159,  159,  159,  159,  159,  161,
    190,  161,  190,  161,  161,  161,  161,  161,  165,  165,
    166,  166,  166,  166,  166,  190,  166,  166,  166,  169,
    169,  169,  169,  169,  190,  169,  190,  169,  173,  173,
    179,  179,  180,  180,  180,  180,  180,  190,  180,  190,

    180,  183,  183,  183,  183,  183,  190,  183,  190,  183,
    185,  185,  185,  185,  185,  190,  185,  185,  185,   23,
    190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
    190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
    190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
    190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
    190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
    190,  190,  190,  190,  190,  190
} ;

static const flex_int16_t yy_chk[677] = {
    0,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    1,    1,    1,    1,    1,    1,    2,    2,    2,    2,
    2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
    2,   44,   44,    2,    2,    2,    2,    2,    2,    2,
    2,    2,    2,    2,    2,    3,    3,    4,    4,    5,
    5,   38,    5,    6,    6,    3,    6,    4,    7,    7,

    38,    7,    8,    8,   38,    8,    9,    9,   38,    9,
    10,   10,  132,   10,   11,   11,   12,   12,   13,   13,
    36,  131,   11,   36,   12,  130,   13,   32,    5,   14,
    14,  129,    6,   15,   15,   16,   16,   14,   32,   32,
    128,   15,  124,   16,   40,   40,   40,   46,   67,   39,
    39,   67,  121,   11,   45,   12,   37,   37,   37,   37,
    39,   42,   42,   42,   40,   46,   37,   37,   37,   37,
    37,   37,   51,   37,   48,   45,   37,   39,   56,   57,
    37,   59,   46,   37,   37,   37,   37,   37,   37,   37,
    118,   62,   45,   90,   48,   84,   51,   57,  163,   56,

    90,   59,   83,   83,   83,  163,   84,   84,   91,   91,
    135,   48,   51,  135,   57,   62,   56,  116,   59,  115,
    99,   99,   99,   99,  100,  100,  103,  103,  103,  164,
    164,   62,   72,   99,   86,  136,   81,   72,  136,  142,
    142,  142,   78,   72,   72,   72,  162,  162,  162,   74,
    99,   72,   70,   72,   72,  168,  168,   72,   72,  170,
    170,   66,   72,  168,   72,   72,   72,   72,   72,   63,
    72,   72,  171,  171,   72,   72,  184,  184,   72,   72,
    72,   72,   89,   89,   89,   89,  172,  172,  172,  178,
    178,  178,   89,   89,   89,   89,   89,   89,  181,  181,

    181,   61,   60,   58,   55,   54,   52,   50,   49,   89,
    89,   89,   89,   89,   89,  165,  165,  165,  165,   47,
    43,   35,   33,  182,  182,  165,  165,  165,  165,  165,
    165,  182,   28,   27,   25,   23,   22,   21,   20,   19,
    18,   17,  165,  165,  165,  165,  165,  165,  167,  167,
    167,  167,    0,    0,    0,    0,    0,    0,  167,  167,
    167,  167,  167,  167,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,  167,  167,  167,  167,  167,
    167,  186,  186,  186,  186,    0,    0,    0,    0,    0,
    0,  186,  186,  186,  186,  186,  186,    0,    0,    0,

    0,    0,    0,    0,    0,    0,    0,    0,  186,  186,
    186,  186,  186,  186,  191,  191,  191,  191,  191,  191,
    191,  191,  191,  192,  192,  192,  192,  192,  192,  192,
    192,  192,  193,  193,  193,  193,  193,  193,  193,  193,
    193,  194,  194,  194,  194,  194,  194,  194,  194,  194,
    195,  195,  195,  195,  195,  195,  195,  195,  195,  196,
    196,  196,  196,  196,  196,  196,  196,  196,  197,  197,
    197,  197,  197,  197,  197,  197,  197,  198,  198,  199,
    0,  199,  199,  199,  199,  199,  199,  199,  200,    0,
    200,  200,  200,  201,    0,  201,  201,  201,  202,    0,

    202,  202,    0,  202,  202,  202,  202,  203,    0,  203,
    203,  203,  203,  203,  203,  203,  204,    0,    0,  204,
    204,  204,  204,  204,  205,    0,    0,  205,  205,  205,
    205,  205,  205,  206,    0,    0,  206,  206,  206,  206,
    206,  206,  207,    0,  207,    0,  207,  207,  207,  207,
    208,    0,  208,    0,  208,  208,  208,  208,  208,  209,
    0,  209,    0,  209,  209,  209,  209,  209,  210,  210,
    211,  211,  211,  211,  211,    0,  211,  211,  211,  212,
    212,  212,  212,  212,    0,  212,    0,  212,  213,  213,
    214,  214,  215,  215,  215,  215,  215,    0,  215,    0,

    215,  216,  216,  216,  216,  216,    0,  216,    0,  216,
    217,  217,  217,  217,  217,    0,  217,  217,  217,  190,
    190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
    190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
    190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
    190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
    190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
    190,  190,  190,  190,  190,  190
} ;

static yy_state_type yy_last_accepting_state;
static char* yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char* yytext;
/******************************************************************************
* z80asm restart
* Copyright (C) Paulo Custodio, 2011-2020
* License: http://www.perlfoundation.org/artistic_license_2_0
* Repository: https://github.com/z88dk/z88dk
******************************************************************************/

/* outer scanner state */
typedef enum state_e { AT_LABEL, AT_OPCODE, AT_OPERAND } state_e;

/* structure for recursive includes */
typedef struct input_t {
    const char*	filename;			/* previous input file name */
    int			lineno;				/* previous input line */
    state_e		state;				/* state of yylex */
    UT_string*	toscan;				/* text to be scanned */
    int			nexttok;			/* next token if peeked, -1 if not */
    YYSTYPE		nextlval;			/* value of next token, if any */
    YY_BUFFER_STATE	buffer;			/* previous input buffer */
} input_t;

/* global state of lex */
const char* yyfilename;
/* int yylineno; // is defined by flex */
static state_e yystate;
static UT_string* yytoscan;
static int yynexttok = -1;
static YYSTYPE yynextlval;
int num_errors;

/* previous buffers */
#define INCLUDE_DEPTH 10
static input_t* input_stack;
static int input_stack_size;
static int input_stack_sp;

/* internal functions */
static void init(void);
static int  return_ident(bool atbol);
static bool parse_integer(const char* text, int base);
static bool parse_bitmap(const char* text);
static void lexerror(const char* fmt, ...);

/* global data */
static UT_string* yypad;
/* C comment - / * .. * / */

/* C-strings, BASIC-strings, SIMPLE-strings */

/* charcater constant, same as double-quoted strings but single quoted and maximum of 1 character */


#define INITIAL 0
#define comment 1
#define str_c 2
#define str_basic 3
#define str_simple 4
#define cc_c 5
#define cc_basic 6
#define cc_simple 7
#define atoctal 8
#define atbinary 9
#define hashhex 10

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE* yyget_in ( void );

void yyset_in  ( FILE* _in_str  );

FILE* yyget_out ( void );

void yyset_out  ( FILE* _out_str  );

int yyget_leng ( void );

char* yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT

static void yyunput ( int c, char* buf_ptr  );

#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char*, const char*, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char* );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL {
    yy_state_type yy_current_state;
    char* yy_cp, *yy_bp;
    int yy_act;

    if ( !(yy_init) ) {
        (yy_init) = 1;

#ifdef YY_USER_INIT
        YY_USER_INIT;
#endif

        if ( ! (yy_start) )
            (yy_start) = 1;	/* first start state */

        if ( ! yyin )
            yyin = stdin;

        if ( ! yyout )
            yyout = stdout;

        if ( ! YY_CURRENT_BUFFER ) {
            yyensure_buffer_stack ();
            YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
        }

        yy_load_buffer_state(  );
    }

    {

        /* setup */
        int yylineno1 = yylineno;
        if (opt_atoctal) BEGIN(atoctal);
        else BEGIN(atbinary);
        if (opt_hashhex) BEGIN(hashhex);

        /* white space */

        while ( /*CONSTCOND*/1 ) {	/* loops until end-of-file is reached */
            yy_cp = (yy_c_buf_p);

            /* Support of yytext. */
            *yy_cp = (yy_hold_char);

            /* yy_bp points to the position in yy_ch_buf of the start of
             * the current run.
             */
            yy_bp = yy_cp;

            yy_current_state = (yy_start);
            yy_current_state += YY_AT_BOL();
yy_match:
            do {
                YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
                if ( yy_accept[yy_current_state] ) {
                    (yy_last_accepting_state) = yy_current_state;
                    (yy_last_accepting_cpos) = yy_cp;
                }
                while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state ) {
                    yy_current_state = (int) yy_def[yy_current_state];
                    if ( yy_current_state >= 191 )
                        yy_c = yy_meta[yy_c];
                }
                yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
                ++yy_cp;
            }
            while ( yy_base[yy_current_state] != 620 );

yy_find_action:
            yy_act = yy_accept[yy_current_state];
            if ( yy_act == 0 ) {
                /* have to back up */
                yy_cp = (yy_last_accepting_cpos);
                yy_current_state = (yy_last_accepting_state);
                yy_act = yy_accept[yy_current_state];
            }

            YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

            switch ( yy_act ) {
            /* beginning of action switch */
            case 0: /* must back up */
                /* undo the effects of YY_DO_BEFORE_ACTION */
                *yy_cp = (yy_hold_char);
                yy_cp = (yy_last_accepting_cpos);
                yy_current_state = (yy_last_accepting_state);
                goto yy_find_action;

            case 1:
                /* rule 1 can match eol */
                YY_RULE_SETUP
                { yylineno++; return '\n'; }
                YY_BREAK
            case 2:
                YY_RULE_SETUP
                { }					/* skip white space */
                YY_BREAK
            case 3:
                YY_RULE_SETUP
                { unput('\n'); yylineno--; }	/* logical line separator */
                YY_BREAK
            /* line comment */
            case 4:
                YY_RULE_SETUP
                { }
                YY_BREAK
            /* C-comment */
            case 5:
                YY_RULE_SETUP
                { BEGIN(comment); yylineno1 = yylineno; }
                YY_BREAK

            case 6:
                /* rule 6 can match eol */
                YY_RULE_SETUP
                { yylineno++; }
                YY_BREAK
            case 7:
                YY_RULE_SETUP
                { }
                YY_BREAK
            case 8:
                YY_RULE_SETUP
                { }
                YY_BREAK
            case 9:
                YY_RULE_SETUP
                { BEGIN(INITIAL); }
                YY_BREAK
            case YY_STATE_EOF(comment):
            { BEGIN(INITIAL); yyerrorat(yyfilename, yylineno1, "unterminated comment"); }
            YY_BREAK

            /* numbers */
            case 10:
                /* rule 10 can match eol */
                *yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
                YY_LINENO_REWIND_TO(yy_cp - 1);
                (yy_c_buf_p) = yy_cp -= 1;
                YY_DO_BEFORE_ACTION; /* set up yytext again */
                YY_RULE_SETUP {
                    yylval.INTEGER = (int)strtol(yytext + 1, NULL, 16); return INTEGER;
                }
                YY_BREAK
            case 11:
                /* rule 11 can match eol */
                *yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
                YY_LINENO_REWIND_TO(yy_cp - 1);
                (yy_c_buf_p) = yy_cp -= 1;
                YY_DO_BEFORE_ACTION; /* set up yytext again */
                YY_RULE_SETUP
                { yylval.INTEGER = (int)strtol(yytext + 1, NULL, 16); return INTEGER; }
                YY_BREAK
            case 12:
                /* rule 12 can match eol */
                *yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
                YY_LINENO_REWIND_TO(yy_cp - 1);
                (yy_c_buf_p) = yy_cp -= 1;
                YY_DO_BEFORE_ACTION; /* set up yytext again */
                YY_RULE_SETUP
                { yylval.INTEGER = (int)strtol(yytext + 1, NULL, 2); return INTEGER; }
                YY_BREAK
            case 13:
                /* rule 13 can match eol */
                *yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
                YY_LINENO_REWIND_TO(yy_cp - 1);
                (yy_c_buf_p) = yy_cp -= 1;
                YY_DO_BEFORE_ACTION; /* set up yytext again */
                YY_RULE_SETUP {
                    yylval.INTEGER = (int)strtol(yytext + 1, NULL, 2); return INTEGER;
                }
                YY_BREAK
            case 14:
                /* rule 14 can match eol */
                *yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
                YY_LINENO_REWIND_TO(yy_cp - 1);
                (yy_c_buf_p) = yy_cp -= 1;
                YY_DO_BEFORE_ACTION; /* set up yytext again */
                YY_RULE_SETUP {
                    yylval.INTEGER = (int)strtol(yytext + 1, NULL, 8); return INTEGER;
                }
                YY_BREAK
            case 15:
                YY_RULE_SETUP
                { if (parse_bitmap(yytext + 2)) return INTEGER; else lexerror("invalid number"); }
                YY_BREAK
            case 16:
                YY_RULE_SETUP {
                    if (parse_bitmap(yytext + 2)) return INTEGER;
                    else lexerror("invalid number"); }
                YY_BREAK
            case 17:
                YY_RULE_SETUP
                { if (parse_integer(yytext + 2,  2)) return INTEGER; else lexerror("invalid number"); }
                YY_BREAK
            case 18:
                YY_RULE_SETUP
                { if (parse_integer(yytext + 2,  8)) return INTEGER; else lexerror("invalid number"); }
                YY_BREAK
            case 19:
                YY_RULE_SETUP
                { if (parse_integer(yytext + 2, 16)) return INTEGER; else lexerror("invalid number"); }
                YY_BREAK
            case 20:
                YY_RULE_SETUP
                { if (parse_integer(yytext,    2)) return INTEGER; else lexerror("invalid number"); }
                YY_BREAK
            case 21:
                YY_RULE_SETUP
                { if (parse_integer(yytext,    8)) return INTEGER; else lexerror("invalid number"); }
                YY_BREAK
            case 22:
                YY_RULE_SETUP
                { if (parse_integer(yytext,   10)) return INTEGER; else lexerror("invalid number"); }
                YY_BREAK
            case 23:
                YY_RULE_SETUP
                { if (parse_integer(yytext,   16)) return INTEGER; else lexerror("invalid number"); }
                YY_BREAK
            case 24:
                YY_RULE_SETUP
                { if (parse_integer(yytext,   10)) return INTEGER; else lexerror("invalid number"); }
                YY_BREAK
            /* alternate registers or identifier */
            case 25:
                YY_RULE_SETUP
                { return return_ident(true); }
                YY_BREAK
            case 26:
            case 27:
            case 28:
            case 29:
            case 30:
            case 31:
            case 32:
            case 33:
            case 34:
            case 35:
            case 36:
            case 37:
                YY_RULE_SETUP
                { return return_ident(false); }
                YY_BREAK
            /* operators */
            case 38:
                YY_RULE_SETUP
                return *yytext;
                YY_BREAK
            case 39:
                YY_RULE_SETUP
                return NE;
                YY_BREAK
            case 40:
                YY_RULE_SETUP
                return NE;
                YY_BREAK
            case 41:
                YY_RULE_SETUP
                return LAND;
                YY_BREAK
            case 42:
                YY_RULE_SETUP
                return LOR;
                YY_BREAK
            case 43:
                YY_RULE_SETUP
                return LXOR;
                YY_BREAK
            case 44:
                YY_RULE_SETUP
                return POW;
                YY_BREAK
            case 45:
                YY_RULE_SETUP
                return '=';
                YY_BREAK
            case 46:
                YY_RULE_SETUP
                return GE;
                YY_BREAK
            case 47:
                YY_RULE_SETUP
                return LE;
                YY_BREAK
            case 48:
                YY_RULE_SETUP
                return LS;
                YY_BREAK
            case 49:
                YY_RULE_SETUP
                return RS;
                YY_BREAK
            /* strings */
            case 50:
                YY_RULE_SETUP {
                    init(); utstring_clear(yypad);
                    switch (opt_string) {
                    case strC: BEGIN(str_c); break;
                    case strBASIC: BEGIN(str_basic); break;
                    case strSIMPLE: BEGIN(str_simple); break;
                    default: assert(0);
                    }
                }
                YY_BREAK

            case 51:
                YY_RULE_SETUP
                { BEGIN(INITIAL); yylval.STRING = spool_add(utstring_body(yypad)); return STRING; }
                YY_BREAK
            case 52:
                /* rule 52 can match eol */
                YY_RULE_SETUP
            case YY_STATE_EOF(str_c):
                YY_RULE_SETUP
            case YY_STATE_EOF(str_basic):
                YY_RULE_SETUP
            case YY_STATE_EOF(str_simple):
            { BEGIN(INITIAL); unput('\n'); lexerror("unterminated string"); }
            YY_BREAK


            case 53:
                YY_RULE_SETUP {
                    int c = (int)strtol(yytext + 1, NULL, 8);
                    if (c > 0xff) {
                        BEGIN(INITIAL);
                        lexerror("octal character constant out of bounds");
                    }
                    else
                        utstring_printf(yypad, "%c", c & 0xff);
                }
                YY_BREAK
            case 54:
                YY_RULE_SETUP {
                    int c = (int)strtol(yytext + 2, NULL, 16);
                    if (c > 0xff) {
                        BEGIN(INITIAL);
                        lexerror("hex character constant out of bounds");
                    }
                    else
                        utstring_printf(yypad, "%c", c & 0xff);
                }
                YY_BREAK
            case 55:
                YY_RULE_SETUP
                { utstring_printf(yypad, "\a"); }
                YY_BREAK
            case 56:
                YY_RULE_SETUP
                { utstring_printf(yypad, "\b"); }
                YY_BREAK
            case 57:
                YY_RULE_SETUP
                { utstring_printf(yypad, "\x1b"); }
                YY_BREAK
            case 58:
                YY_RULE_SETUP
                { utstring_printf(yypad, "\f"); }
                YY_BREAK
            case 59:
                YY_RULE_SETUP
                { utstring_printf(yypad, "\n"); }
                YY_BREAK
            case 60:
                YY_RULE_SETUP
                { utstring_printf(yypad, "\r"); }
                YY_BREAK
            case 61:
                YY_RULE_SETUP
                { utstring_printf(yypad, "\t"); }
                YY_BREAK
            case 62:
                YY_RULE_SETUP
                { utstring_printf(yypad, "\v"); }
                YY_BREAK
            case 63:
                YY_RULE_SETUP
                { utstring_printf(yypad, "\\"); }
                YY_BREAK
            case 64:
                YY_RULE_SETUP
                { utstring_printf(yypad, "'"); }
                YY_BREAK
            case 65:
                YY_RULE_SETUP
                { utstring_printf(yypad, "\""); }
                YY_BREAK
            case 66:
                YY_RULE_SETUP
                { utstring_printf(yypad, "?"); }
                YY_BREAK
            case 67:
                YY_RULE_SETUP {
                    BEGIN(INITIAL);
                    lexerror("bad escape sequence"); }
                YY_BREAK


            case 68:
                YY_RULE_SETUP
                { utstring_printf(yypad, "%s", yytext); }
                YY_BREAK


            case 69:
                YY_RULE_SETUP
                { utstring_printf(yypad, "\""); }
                YY_BREAK
            case 70:
                YY_RULE_SETUP
                { utstring_printf(yypad, "%s", yytext); }
                YY_BREAK


            case 71:
                YY_RULE_SETUP
                { utstring_printf(yypad, "%s", yytext); }
                YY_BREAK

            /* character constants */
            case 72:
                YY_RULE_SETUP {
                    init(); utstring_clear(yypad);
                    switch (opt_string) {
                    case strC: BEGIN(cc_c); break;
                    case strBASIC: BEGIN(cc_basic); break;
                    case strSIMPLE: BEGIN(cc_simple); break;
                    default: assert(0);
                    }
                }
                YY_BREAK

            case 73:
                YY_RULE_SETUP {
                    BEGIN(INITIAL);
                    if (utstring_len(yypad) != 1)
                        lexerror("character constant must have size 1");
                    else {
                        yylval.INTEGER = (unsigned char) * utstring_body(yypad);
                        return INTEGER;
                    }
                }
                YY_BREAK
            case 74:
                /* rule 74 can match eol */
                YY_RULE_SETUP
            case YY_STATE_EOF(cc_c):
                YY_RULE_SETUP
            case YY_STATE_EOF(cc_basic):
                YY_RULE_SETUP
            case YY_STATE_EOF(cc_simple):
            { BEGIN(INITIAL); unput('\n'); lexerror("unterminated character constant"); }
            YY_BREAK


            case 75:
                YY_RULE_SETUP
                { utstring_printf(yypad, "%s", yytext); }
                YY_BREAK


            case 76:
                YY_RULE_SETUP
                { utstring_printf(yypad, "'"); }
                YY_BREAK
            case 77:
                YY_RULE_SETUP
                { utstring_printf(yypad, "%s", yytext); }
                YY_BREAK


            case 78:
                YY_RULE_SETUP
                { utstring_printf(yypad, "%s", yytext); }
                YY_BREAK

            case 79:
                YY_RULE_SETUP
                lexerror("invalid character");
                YY_BREAK
            case 80:
                YY_RULE_SETUP
                YY_FATAL_ERROR( "flex scanner jammed" );
                YY_BREAK
            case YY_STATE_EOF(INITIAL):
            case YY_STATE_EOF(atoctal):
            case YY_STATE_EOF(atbinary):
            case YY_STATE_EOF(hashhex):
                yyterminate();

            case YY_END_OF_BUFFER: {
                /* Amount of text matched not including the EOB char. */
                int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

                /* Undo the effects of YY_DO_BEFORE_ACTION. */
                *yy_cp = (yy_hold_char);
                YY_RESTORE_YY_MORE_OFFSET

                if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW ) {
                    /* We're scanning a new file or input source.  It's
                     * possible that this happened because the user
                     * just pointed yyin at a new source and called
                     * yylex().  If so, then we have to assure
                     * consistency between YY_CURRENT_BUFFER and our
                     * globals.  Here is the right place to do so, because
                     * this is the first action (other than possibly a
                     * back-up) that will match for the new input source.
                     */
                    (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
                    YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
                    YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
                }

                /* Note that here we test for yy_c_buf_p "<=" to the position
                 * of the first EOB in the buffer, since yy_c_buf_p will
                 * already have been incremented past the NUL character
                 * (since all states make transitions on EOB to the
                 * end-of-buffer state).  Contrast this with the test
                 * in input().
                 */
                if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] ) {
                    /* This was really a NUL. */
                    yy_state_type yy_next_state;

                    (yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

                    yy_current_state = yy_get_previous_state(  );

                    /* Okay, we're now positioned to make the NUL
                     * transition.  We couldn't have
                     * yy_get_previous_state() go ahead and do it
                     * for us because it doesn't know how to deal
                     * with the possibility of jamming (and we don't
                     * want to build jamming into it because then it
                     * will run more slowly).
                     */

                    yy_next_state = yy_try_NUL_trans( yy_current_state );

                    yy_bp = (yytext_ptr) + YY_MORE_ADJ;

                    if ( yy_next_state ) {
                        /* Consume the NUL. */
                        yy_cp = ++(yy_c_buf_p);
                        yy_current_state = yy_next_state;
                        goto yy_match;
                    }

                    else {
                        yy_cp = (yy_c_buf_p);
                        goto yy_find_action;
                    }
                }

                else switch ( yy_get_next_buffer(  ) ) {
                    case EOB_ACT_END_OF_FILE: {
                        (yy_did_buffer_switch_on_eof) = 0;

                        if ( yywrap(  ) ) {
                            /* Note: because we've taken care in
                             * yy_get_next_buffer() to have set up
                             * yytext, we can now set up
                             * yy_c_buf_p so that if some total
                             * hoser (like flex itself) wants to
                             * call the scanner after we return the
                             * YY_NULL, it'll still work - another
                             * YY_NULL will get returned.
                             */
                            (yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

                            yy_act = YY_STATE_EOF(YY_START);
                            goto do_action;
                        }

                        else {
                            if ( ! (yy_did_buffer_switch_on_eof) )
                                YY_NEW_FILE;
                        }
                        break;
                    }

                    case EOB_ACT_CONTINUE_SCAN:
                        (yy_c_buf_p) =
                            (yytext_ptr) + yy_amount_of_matched_text;

                        yy_current_state = yy_get_previous_state(  );

                        yy_cp = (yy_c_buf_p);
                        yy_bp = (yytext_ptr) + YY_MORE_ADJ;
                        goto yy_match;

                    case EOB_ACT_LAST_MATCH:
                        (yy_c_buf_p) =
                            &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

                        yy_current_state = yy_get_previous_state(  );

                        yy_cp = (yy_c_buf_p);
                        yy_bp = (yytext_ptr) + YY_MORE_ADJ;
                        goto yy_find_action;
                    }
                break;
            }

            default:
                YY_FATAL_ERROR(
                    "fatal flex scanner internal error--no action found" );
            } /* end of action switch */
        } /* end of scanning one token */
    } /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void) {
    char* dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
    char* source = (yytext_ptr);
    int number_to_move, i;
    int ret_val;

    if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
        YY_FATAL_ERROR(
            "fatal flex scanner internal error--end of buffer missed" );

    if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 ) {
        /* Don't try to fill the buffer, so this is an EOF. */
        if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 ) {
            /* We matched a single character, the EOB, so
             * treat this as a final EOF.
             */
            return EOB_ACT_END_OF_FILE;
        }

        else {
            /* We matched some text prior to the EOB, first
             * process it.
             */
            return EOB_ACT_LAST_MATCH;
        }
    }

    /* Try to read more data. */

    /* First move last chars to start of buffer. */
    number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

    for ( i = 0; i < number_to_move; ++i )
        *(dest++) = *(source++);

    if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
        /* don't do the read, it's not guaranteed to return an EOF,
         * just force an EOF
         */
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

    else {
        int num_to_read =
            YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

        while ( num_to_read <= 0 ) {
            /* Not enough room in the buffer - grow it. */

            /* just a shorter name for the current buffer */
            YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

            int yy_c_buf_p_offset =
                (int) ((yy_c_buf_p) - b->yy_ch_buf);

            if ( b->yy_is_our_buffer ) {
                int new_size = b->yy_buf_size * 2;

                if ( new_size <= 0 )
                    b->yy_buf_size += b->yy_buf_size / 8;
                else
                    b->yy_buf_size *= 2;

                b->yy_ch_buf = (char*)
                               /* Include room in for 2 EOB chars. */
                               yyrealloc( (void*) b->yy_ch_buf,
                                          (yy_size_t) (b->yy_buf_size + 2)  );
            }
            else
                /* Can't grow it, we don't own it. */
                b->yy_ch_buf = NULL;

            if ( ! b->yy_ch_buf )
                YY_FATAL_ERROR(
                    "fatal error - scanner input buffer overflow" );

            (yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

            num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
                          number_to_move - 1;

        }

        if ( num_to_read > YY_READ_BUF_SIZE )
            num_to_read = YY_READ_BUF_SIZE;

        /* Read in more data. */
        YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
                  (yy_n_chars), num_to_read );

        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
    }

    if ( (yy_n_chars) == 0 ) {
        if ( number_to_move == YY_MORE_ADJ ) {
            ret_val = EOB_ACT_END_OF_FILE;
            yyrestart( yyin  );
        }

        else {
            ret_val = EOB_ACT_LAST_MATCH;
            YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
                YY_BUFFER_EOF_PENDING;
        }
    }

    else
        ret_val = EOB_ACT_CONTINUE_SCAN;

    if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
        /* Extend the array by 50%, plus the number we really need. */
        int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
        YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char*) yyrealloc(
                (void*) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
        if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
            YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
        /* "- 2" to take care of EOB's */
        YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
    }

    (yy_n_chars) += number_to_move;
    YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
    YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

    (yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

    return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state (void) {
    yy_state_type yy_current_state;
    char* yy_cp;

    yy_current_state = (yy_start);
    yy_current_state += YY_AT_BOL();

    for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp ) {
        YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
        if ( yy_accept[yy_current_state] ) {
            (yy_last_accepting_state) = yy_current_state;
            (yy_last_accepting_cpos) = yy_cp;
        }
        while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state ) {
            yy_current_state = (int) yy_def[yy_current_state];
            if ( yy_current_state >= 191 )
                yy_c = yy_meta[yy_c];
        }
        yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    }

    return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state ) {
    int yy_is_jam;
    char* yy_cp = (yy_c_buf_p);

    YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] ) {
        (yy_last_accepting_state) = yy_current_state;
        (yy_last_accepting_cpos) = yy_cp;
    }
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state ) {
        yy_current_state = (int) yy_def[yy_current_state];
        if ( yy_current_state >= 191 )
            yy_c = yy_meta[yy_c];
    }
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 190);

    return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

static void yyunput (int c, char* yy_bp ) {
    char* yy_cp;

    yy_cp = (yy_c_buf_p);

    /* undo effects of setting up yytext */
    *yy_cp = (yy_hold_char);

    if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 ) {
        /* need to shift things up to make room */
        /* +2 for EOB chars. */
        int number_to_move = (yy_n_chars) + 2;
        char* dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
                  YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
        char* source =
            &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

        while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
            *--dest = *--source;

        yy_cp += (int) (dest - source);
        yy_bp += (int) (dest - source);
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
            (yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

        if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
            YY_FATAL_ERROR( "flex scanner push-back overflow" );
    }

    *--yy_cp = (char) c;

    (yytext_ptr) = yy_bp;
    (yy_hold_char) = *yy_cp;
    (yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput (void)
#else
static int input  (void)
#endif

{
    int c;

    *(yy_c_buf_p) = (yy_hold_char);

    if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR ) {
        /* yy_c_buf_p now points to the character we want to return.
         * If this occurs *before* the EOB characters, then it's a
         * valid NUL; if not, then we've hit the end of the buffer.
         */
        if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
            /* This was really a NUL. */
            *(yy_c_buf_p) = '\0';

        else {
            /* need more input */
            int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
            ++(yy_c_buf_p);

            switch ( yy_get_next_buffer(  ) ) {
            case EOB_ACT_LAST_MATCH:
                /* This happens because yy_g_n_b()
                 * sees that we've accumulated a
                 * token and flags that we need to
                 * try matching the token before
                 * proceeding.  But for input(),
                 * there's no matching to consider.
                 * So convert the EOB_ACT_LAST_MATCH
                 * to EOB_ACT_END_OF_FILE.
                 */

                /* Reset buffer status. */
                yyrestart( yyin );

            /*FALLTHROUGH*/

            case EOB_ACT_END_OF_FILE: {
                if ( yywrap(  ) )
                    return 0;

                if ( ! (yy_did_buffer_switch_on_eof) )
                    YY_NEW_FILE;
#ifdef __cplusplus
                return yyinput();
#else
                return input();
#endif
            }

            case EOB_ACT_CONTINUE_SCAN:
                (yy_c_buf_p) = (yytext_ptr) + offset;
                break;
            }
        }
    }

    c = *(unsigned char*) (yy_c_buf_p);	/* cast for 8-bit char's */
    *(yy_c_buf_p) = '\0';	/* preserve yytext */
    (yy_hold_char) = *++(yy_c_buf_p);

    YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

    return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 *
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyrestart  (FILE* input_file ) {

    if ( ! YY_CURRENT_BUFFER ) {
        yyensure_buffer_stack ();
        YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
    }

    yy_init_buffer( YY_CURRENT_BUFFER, input_file );
    yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 *
 */
void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer ) {

    /* TODO. We should be able to replace this entire function body
     * with
     *		yypop_buffer_state();
     *		yypush_buffer_state(new_buffer);
     */
    yyensure_buffer_stack ();
    if ( YY_CURRENT_BUFFER == new_buffer )
        return;

    if ( YY_CURRENT_BUFFER ) {
        /* Flush out information for old buffer. */
        *(yy_c_buf_p) = (yy_hold_char);
        YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
    }

    YY_CURRENT_BUFFER_LVALUE = new_buffer;
    yy_load_buffer_state(  );

    /* We don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    (yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void) {
    (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
    (yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
    yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
    (yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 *
 * @return the allocated buffer state.
 */
YY_BUFFER_STATE yy_create_buffer  (FILE* file, int  size ) {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
    if ( ! b )
        YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (char*) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
    if ( ! b->yy_ch_buf )
        YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_is_our_buffer = 1;

    yy_init_buffer( b, file );

    return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 *
 */
void yy_delete_buffer (YY_BUFFER_STATE  b ) {

    if ( ! b )
        return;

    if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
        YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

    if ( b->yy_is_our_buffer )
        yyfree( (void*) b->yy_ch_buf  );

    yyfree( (void*) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE* file )

{
    int oerrno = errno;

    yy_flush_buffer( b );

    b->yy_input_file = file;
    b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER) {
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

    b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;

    errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 *
 */
void yy_flush_buffer (YY_BUFFER_STATE  b ) {
    if ( ! b )
        return;

    b->yy_n_chars = 0;

    /* We always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[0];

    b->yy_at_bol = 1;
    b->yy_buffer_status = YY_BUFFER_NEW;

    if ( b == YY_CURRENT_BUFFER )
        yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer ) {
    if (new_buffer == NULL)
        return;

    yyensure_buffer_stack();

    /* This block is copied from yy_switch_to_buffer. */
    if ( YY_CURRENT_BUFFER ) {
        /* Flush out information for old buffer. */
        *(yy_c_buf_p) = (yy_hold_char);
        YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
    }

    /* Only push if top exists. Otherwise, replace top. */
    if (YY_CURRENT_BUFFER)
        (yy_buffer_stack_top)++;
    YY_CURRENT_BUFFER_LVALUE = new_buffer;

    /* copied from yy_switch_to_buffer. */
    yy_load_buffer_state(  );
    (yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *
 */
void yypop_buffer_state (void) {
    if (!YY_CURRENT_BUFFER)
        return;

    yy_delete_buffer(YY_CURRENT_BUFFER );
    YY_CURRENT_BUFFER_LVALUE = NULL;
    if ((yy_buffer_stack_top) > 0)
        --(yy_buffer_stack_top);

    if (YY_CURRENT_BUFFER) {
        yy_load_buffer_state(  );
        (yy_did_buffer_switch_on_eof) = 1;
    }
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void) {
    yy_size_t num_to_alloc;

    if (!(yy_buffer_stack)) {

        /* First allocation is just for 2 elements, since we don't know if this
         * scanner will even need a stack. We use 2 instead of 1 to avoid an
         * immediate realloc on the next call.
         */
        num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
        (yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
                            (num_to_alloc * sizeof(struct yy_buffer_state*)
                            );
        if ( ! (yy_buffer_stack) )
            YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

        memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

        (yy_buffer_stack_max) = num_to_alloc;
        (yy_buffer_stack_top) = 0;
        return;
    }

    if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1) {

        /* Increase the buffer to prepare for a possible push. */
        yy_size_t grow_size = 8 /* arbitrary grow size */;

        num_to_alloc = (yy_buffer_stack_max) + grow_size;
        (yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
                            ((yy_buffer_stack),
                             num_to_alloc * sizeof(struct yy_buffer_state*)
                            );
        if ( ! (yy_buffer_stack) )
            YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

        /* zero only the new slots.*/
        memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
        (yy_buffer_stack_max) = num_to_alloc;
    }
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char* base, yy_size_t  size ) {
    YY_BUFFER_STATE b;

    if ( size < 2 ||
            base[size - 2] != YY_END_OF_BUFFER_CHAR ||
            base[size - 1] != YY_END_OF_BUFFER_CHAR )
        /* They forgot to leave room for the EOB's. */
        return NULL;

    b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
    if ( ! b )
        YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

    b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
    b->yy_buf_pos = b->yy_ch_buf = base;
    b->yy_is_our_buffer = 0;
    b->yy_input_file = NULL;
    b->yy_n_chars = b->yy_buf_size;
    b->yy_is_interactive = 0;
    b->yy_at_bol = 1;
    b->yy_fill_buffer = 0;
    b->yy_buffer_status = YY_BUFFER_NEW;

    yy_switch_to_buffer( b  );

    return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 *
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char* yystr ) {

    return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char* yybytes, int  _yybytes_len ) {
    YY_BUFFER_STATE b;
    char* buf;
    yy_size_t n;
    int i;

    /* Get memory for full buffer, including space for trailing EOB's. */
    n = (yy_size_t) (_yybytes_len + 2);
    buf = (char*) yyalloc( n  );
    if ( ! buf )
        YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

    for ( i = 0; i < _yybytes_len; ++i )
        buf[i] = yybytes[i];

    buf[_yybytes_len] = buf[_yybytes_len + 1] = YY_END_OF_BUFFER_CHAR;

    b = yy_scan_buffer( buf, n );
    if ( ! b )
        YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

    /* It's okay to grow etc. this buffer, and we should throw it
     * away when we're done.
     */
    b->yy_is_our_buffer = 1;

    return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg ) {
    fprintf( stderr, "%s\n", msg );
    exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 *
 */
int yyget_lineno  (void) {

    return yylineno;
}

/** Get the input stream.
 *
 */
FILE* yyget_in  (void) {
    return yyin;
}

/** Get the output stream.
 *
 */
FILE* yyget_out  (void) {
    return yyout;
}

/** Get the length of the current token.
 *
 */
int yyget_leng  (void) {
    return yyleng;
}

/** Get the current token.
 *
 */

char* yyget_text  (void) {
    return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 *
 */
void yyset_lineno (int  _line_number ) {

    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 *
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE*   _in_str ) {
    yyin = _in_str ;
}

void yyset_out (FILE*   _out_str ) {
    yyout = _out_str ;
}

int yyget_debug  (void) {
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug ) {
    yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void) {
    /* Initialization is the same as for the non-reentrant scanner.
    * This function is called from yylex_destroy(), so don't allocate here.
    */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    /* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void) {

    /* Pop the buffer stack, destroying each element. */
    while(YY_CURRENT_BUFFER) {
        yy_delete_buffer( YY_CURRENT_BUFFER  );
        YY_CURRENT_BUFFER_LVALUE = NULL;
        yypop_buffer_state();
    }

    /* Destroy the stack itself. */
    yyfree((yy_buffer_stack) );
    (yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char* s2, int n ) {

    int i;
    for ( i = 0; i < n; ++i )
        s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char* s ) {
    int n;
    for ( n = 0; s[n]; ++n )
        ;

    return n;
}
#endif

void* yyalloc (yy_size_t  size ) {
    return malloc(size);
}

void* yyrealloc  (void* ptr, yy_size_t  size ) {

    /* The cast to (char *) in the following accommodates both
     * implementations that use char* generic pointers, and those
     * that use void* generic pointers.  It works with the latter
     * because both ANSI C and C++ allow castless assignment from
     * any pointer type to void*, and deal with argument conversions
     * as though doing an assignment.
     */
    return realloc(ptr, size);
}

void yyfree (void* ptr ) {
    free( (char*) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"



/*---------------------------------------------------------------------------*/

static void dtor(void) {
    /* free UT_string yypad */
    utstring_free(yypad);

    /* free input_stack */
    while (input_stack_sp > 0)
        pop_input_file();
    free(input_stack); input_stack = NULL;
    input_stack_size = input_stack_sp = 0;

    /* free toscan buffer */
    utstring_free(yytoscan);
}

static void init(void) {
    static bool inited = false;
    if (!inited) {
        utstring_new(yypad);
        utstring_new(yytoscan);

        atexit(dtor);
        inited = true;
    }
}

/*---------------------------------------------------------------------------*/

int yywrap(void) {
    return 1;
}

static int return_ident(bool atbol) {
    init();

    // convert copy of yytext to upper case to lookup
    utstring_clear(yypad);
    utstring_bincpy(yypad, yytext, yyleng);
    strtoupper(utstring_body(yypad));

    if (opt_ucase)
        yylval.IDENT.name = spool_add(utstring_body(yypad));
    else
        yylval.IDENT.name = spool_add(yytext);

    yylval.IDENT.id = lookup_keyword(utstring_body(yypad));
    yylval.IDENT.atbol = atbol;
    return IDENT;
}

static bool parse_integer(const char* text, int base) {
    /* convert number */
    yylval.INTEGER = (int)strtol(text, NULL, base);

    /* peek next character */
    char c = input();
    if (c != 0) unput(c);

    if (c == '.' || c == '_' || isalnum(c))
        return false;
    else
        return true;
}

static bool parse_bitmap(const char* text) {
    init();

    /* convert number */
    yylval.INTEGER = 0;
    const char* p;
    for (p = text; *p; p++) {
        if (*p == '-') yylval.INTEGER *= 2;
        else if (*p == '#') yylval.INTEGER = yylval.INTEGER * 2 + 1;
        else break;
    }

    if (*p == '"')
        return true;
    else
        return false;
}

/*---------------------------------------------------------------------------*/

void push_input_file(const char* filename) {
    init();

    /* TODO: search include path */

    /* grow stack if needed */
    if (input_stack_sp >= input_stack_size) {
        input_stack_size += INCLUDE_DEPTH;
        input_stack = xrealloc(input_stack, input_stack_size * sizeof(input_t));
    }

    /* open the file, get its size */
    FILE* in = fopen(filename, "rb");
    if (in == NULL) {
        perror(filename);
        yyerror("open failed");
        exit(EXIT_FAILURE);
    }

    fseek(in, 0, SEEK_END);
    int size = ftell(in);
    if (size < 0) {
        perror(filename);
        yyerror("seek failed");
        exit(EXIT_FAILURE);
    }
    fseek(in, 0, SEEK_SET);

    /* save current input */
    input_t* input = &input_stack[input_stack_sp++];
    input->filename = yyfilename;
    input->lineno = yylineno;
    input->state = yystate;
    input->toscan = yytoscan;
    input->nexttok = yynexttok;
    input->nextlval = yynextlval;
    input->buffer = YY_CURRENT_BUFFER;

    /* slurp whole file */
    utstring_new(yytoscan);
    utstring_reserve(yytoscan, size + 4);		/* +1 newline +2 NUL end-of-buffer +1 for std NUL */
    if (size != fread(utstring_body(yytoscan), 1, size, in)) {
        perror(filename);
        yyerror("read failed");
        exit(EXIT_FAILURE);
    }
    utstring_len(yytoscan) = size;
    fclose(in);

    /* append newline and 2 NULs required by yylex */
    if (size > 0 && utstring_body(yytoscan)[size - 1] != '\n')
        utstring_bincpy(yytoscan, "\n", 1);
    utstring_bincpy(yytoscan, "\0\0", 2);		/* 2 EOB needed by yylex */

    /* set current buffer */
    yyfilename = spool_add(filename);
    yylineno = 1;
    yystate = AT_LABEL;
    yynexttok = -1;
    YY_BUFFER_STATE buffer = yy_scan_buffer(utstring_body(yytoscan), utstring_len(yytoscan));
    if (buffer == NULL)
        YY_FATAL_ERROR("yy_scan_buffer() failed");
}

void pop_input_file(void) {
    if (input_stack_sp > 0) {
        yy_delete_buffer(YY_CURRENT_BUFFER);

        input_t* input = &input_stack[--input_stack_sp];
        utstring_free(yytoscan);
        yytoscan = input->toscan;
        yyfilename = input->filename;
        yylineno = input->lineno;
        yystate = input->state;
        yynexttok = input->nexttok;
        yynextlval = input->nextlval;
        yy_switch_to_buffer(input->buffer);
    }
}

/*---------------------------------------------------------------------------*/

static void prefix_at(const char* filename, int lineno, const char* prefix) {
    bool have_prefix;
    if (!STREMPTY(filename)) {
        fprintf(stderr, "%s:", filename);
        have_prefix = true;
    }
    if (lineno) {
        fprintf(stderr, "%d:", lineno);
        have_prefix = true;
    }
    if (have_prefix)
        fprintf(stderr, " ");
    fprintf(stderr, "%s: ", prefix);
}

static void error_prefix_at(const char* filename, int lineno) {
    prefix_at(filename, lineno, "error");
}

static void warn_prefix_at(const char* filename, int lineno) {
    prefix_at(filename, lineno, "warning");
}

#define DO_ERROR(file, line) \
	va_list ap; \
	va_start(ap, fmt); \
	error_prefix_at((file), (line)); \
	vfprintf(stderr, fmt, ap); \
	va_end(ap); \
	fprintf(stderr, "\n"); \
	num_errors++

void yyerror(const char* fmt, ...) {
    DO_ERROR(yyfilename, yylineno);
}

void yyerrorat(const char* filename, int lineno, const char* fmt, ...) {
    DO_ERROR(filename, lineno);
}

// yyerror and skip to end of line
static void lexerror(const char* fmt, ...) {
    DO_ERROR(yyfilename, yylineno);
    int c;
    while ((c = input()) != 0 && c != '\n') {
    }
    if (c != 0)
        unput(c);
}

#undef DO_ERROR

/*---------------------------------------------------------------------------*/

static int peek_token(void) {
    YYSTYPE savelval = yylval;
    yynexttok = yylex_1();
    yynextlval = yylval;
    yylval = savelval;
    return yynexttok;
}

static int get_next_token(void) {
    assert(yynexttok >= 0);
    int tok = yynexttok;
    yynexttok = -1;
    yylval = yynextlval;
    return tok;
}

static void clear_queue(void) {
    yynexttok = -1;
}

int yylex(void) {
    /* get next token */
    int tok = (yynexttok >= 0) ? get_next_token() : yylex_1();
    switch (yystate) {
    case AT_LABEL:
        switch (tok) {
        case '.':
            switch (peek_token()) {
            case IDENT:
                if (opt_dotdirective && is_directive(yynextlval.IDENT.id)) {
                    yystate = AT_OPERAND;
                    clear_queue();
                    return yynextlval.IDENT.id;
                }
                else {
                    yystate = AT_OPCODE;
                    yylval.LABEL = yynextlval.IDENT.name;
                    clear_queue();
                    return LABEL;
                }
            default:
                yystate = AT_OPERAND;
                return tok;
            }
        case IDENT:
            if (opt_labelcol1 && yylval.IDENT.atbol) {
                yystate = AT_OPCODE;
                yylval.LABEL = yylval.IDENT.name;
                return LABEL;
            }
            else {
                switch (peek_token()) {
                case ':': {
                    yystate = AT_OPCODE;
                    yylval.LABEL = yylval.IDENT.name;
                    clear_queue();
                    return LABEL;
                }
                case IDENT: {
                    if (is_opcode_or_directive(yynextlval.IDENT.id)) {		/* LABEL OPCODE */
                        yystate = AT_OPCODE;
                        yylval.LABEL = yylval.IDENT.name;
                        return LABEL;
                    }
                    else {							/* OPCODE IDENT */
                        yystate = AT_OPERAND;
                        return (is_opcode_or_directive(yylval.IDENT.id)) ?
                               yylval.IDENT.id : IDENT;
                    }
                }
                default:
                    yystate = AT_OPERAND;
                    return (is_opcode_or_directive(yylval.IDENT.id)) ?
                           yylval.IDENT.id : IDENT;
                }
            }
        case '\n':
            yystate = AT_LABEL;
            return tok;
        default:
            yystate = AT_OPERAND;
            return tok;
        }
    case AT_OPCODE:
        switch (tok) {
        case IDENT:
            yystate = AT_OPERAND;
            return (is_opcode_or_directive(yylval.IDENT.id)) ?
                   yylval.IDENT.id : IDENT;
        case '\n':
            yystate = AT_LABEL;
            return tok;
        default:
            return tok;
        }
    case AT_OPERAND:
        switch (tok) {
        case '\n':
            yystate = AT_LABEL;
            return tok;
        case IDENT:
            return (is_flag_or_register(yylval.IDENT.id)) ?
                   yylval.IDENT.id : IDENT;
        default:
            return tok;
        }
    default:
        assert(0); return 0;
    }
}

